// Copyright (c) 2026 RAMTT (Malte Therkildsen)
// Licensed under MIT OR Apache-2.0. See LICENSE-MIT and LICENSE-APACHE.

// @ramtt/icons — Icon catalog metadata (333 icons × 28 categories)

export interface IconMeta {
  name: string
  category: string
  tags: string[]
  hasLine: boolean
  hasSolid: boolean
  hasDuo: boolean
  hasAnimated: boolean
}

export const ICON_CATEGORIES = [
  'navigation',
  'action',
  'arrow',
  'status',
  'communication',
  'media',
  'file',
  'user',
  'layout',
  'data',
  'device',
  'weather',
  'commerce',
  'toggle',
  'misc',
  'sport-domain',
  'sport-training',
  'sport-nutrition',
  'sport-body',
  'navigation-app',
  'sort',
  'form',
  'social',
  'feedback',
  'sport-race',
  'sport-biochem',
  'security',
  'achievement',
  'activity',
  'food',
] as const

export const ICON_CATALOG: IconMeta[] = [
  // ─── navigation (5) ────────────────────────────────────────────────
  {
    name: 'IconToday',
    category: 'navigation',
    tags: ['today', 'date', 'now', 'current'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCalendar',
    category: 'navigation',
    tags: ['calendar', 'date', 'schedule', 'planner'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconAnalytics',
    category: 'navigation',
    tags: ['analytics', 'dashboard', 'stats', 'insights'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFuel',
    category: 'navigation',
    tags: ['fuel', 'nutrition', 'energy', 'carbs'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSettings',
    category: 'navigation',
    tags: ['settings', 'preferences', 'config', 'gear', 'cog'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── action (13) ───────────────────────────────────────────────────
  {
    name: 'IconPlus',
    category: 'action',
    tags: ['plus', 'add', 'create', 'new'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconClose',
    category: 'action',
    tags: ['close', 'dismiss', 'remove', 'x'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSearch',
    category: 'action',
    tags: ['search', 'find', 'lookup', 'magnifier'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFilter',
    category: 'action',
    tags: ['filter', 'funnel', 'sort', 'refine'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconEdit',
    category: 'action',
    tags: ['edit', 'pencil', 'modify', 'write'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTrash',
    category: 'action',
    tags: ['trash', 'delete', 'remove', 'bin'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCopy',
    category: 'action',
    tags: ['copy', 'duplicate', 'clipboard', 'paste'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDownload',
    category: 'action',
    tags: ['download', 'save', 'export', 'arrow-down'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconUpload',
    category: 'action',
    tags: ['upload', 'import', 'arrow-up', 'send'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: true,
  },
  {
    name: 'IconExpand',
    category: 'action',
    tags: ['expand', 'fullscreen', 'maximize', 'enlarge'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCollapse',
    category: 'action',
    tags: ['collapse', 'minimize', 'shrink', 'reduce'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMoreHorizontal',
    category: 'action',
    tags: ['more', 'dots', 'ellipsis', 'menu', 'options'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconGrip',
    category: 'action',
    tags: ['grip', 'drag', 'handle', 'reorder', 'move'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── arrow (6) ─────────────────────────────────────────────────────
  {
    name: 'IconChevronLeft',
    category: 'arrow',
    tags: ['chevron', 'left', 'back', 'previous'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconChevronRight',
    category: 'arrow',
    tags: ['chevron', 'right', 'next', 'forward'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconChevronDown',
    category: 'arrow',
    tags: ['chevron', 'down', 'dropdown', 'expand'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconChevronUp',
    category: 'arrow',
    tags: ['chevron', 'up', 'collapse', 'above'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconArrowLeft',
    category: 'arrow',
    tags: ['arrow', 'left', 'back', 'navigate'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconArrowRight',
    category: 'arrow',
    tags: ['arrow', 'right', 'forward', 'navigate'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── status (4) ────────────────────────────────────────────────────
  {
    name: 'IconCheck',
    category: 'status',
    tags: ['check', 'done', 'success', 'complete', 'tick'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: true,
  },
  {
    name: 'IconAlertTriangle',
    category: 'status',
    tags: ['alert', 'warning', 'triangle', 'caution'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconInfo',
    category: 'status',
    tags: ['info', 'information', 'help', 'about'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconAlertCircle',
    category: 'status',
    tags: ['alert', 'error', 'circle', 'danger', 'exclamation'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── communication (8) ─────────────────────────────────────────────
  {
    name: 'IconMail',
    category: 'communication',
    tags: ['mail', 'email', 'envelope', 'message'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSend',
    category: 'communication',
    tags: ['send', 'submit', 'paper-plane', 'dispatch'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMessageCircle',
    category: 'communication',
    tags: ['message', 'chat', 'bubble', 'circle', 'comment'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMessageSquare',
    category: 'communication',
    tags: ['message', 'chat', 'bubble', 'square', 'comment'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPhone',
    category: 'communication',
    tags: ['phone', 'call', 'telephone', 'contact'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconVideo',
    category: 'communication',
    tags: ['video', 'camera', 'record', 'meeting'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconShare',
    category: 'communication',
    tags: ['share', 'forward', 'distribute', 'social'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLink',
    category: 'communication',
    tags: ['link', 'url', 'chain', 'hyperlink', 'connect'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── media (6) ─────────────────────────────────────────────────────
  {
    name: 'IconImage',
    category: 'media',
    tags: ['image', 'photo', 'picture', 'gallery'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCamera',
    category: 'media',
    tags: ['camera', 'photo', 'capture', 'snapshot'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPlay',
    category: 'media',
    tags: ['play', 'start', 'video', 'media'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPause',
    category: 'media',
    tags: ['pause', 'stop', 'halt', 'media'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconVolume',
    category: 'media',
    tags: ['volume', 'sound', 'audio', 'speaker'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMic',
    category: 'media',
    tags: ['mic', 'microphone', 'audio', 'voice', 'record'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── file (6) ──────────────────────────────────────────────────────
  {
    name: 'IconFile',
    category: 'file',
    tags: ['file', 'document', 'page', 'blank'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFileText',
    category: 'file',
    tags: ['file', 'text', 'document', 'content', 'article'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFolder',
    category: 'file',
    tags: ['folder', 'directory', 'organize', 'group'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFolderOpen',
    category: 'file',
    tags: ['folder', 'open', 'directory', 'browse'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconClipboard',
    category: 'file',
    tags: ['clipboard', 'paste', 'copy', 'board'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconArchive',
    category: 'file',
    tags: ['archive', 'box', 'storage', 'compress'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── user (5) ──────────────────────────────────────────────────────
  {
    name: 'IconUser',
    category: 'user',
    tags: ['user', 'person', 'profile', 'account'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconUsers',
    category: 'user',
    tags: ['users', 'people', 'group', 'team', 'members'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconUserPlus',
    category: 'user',
    tags: ['user', 'add', 'invite', 'new-member'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconUserMinus',
    category: 'user',
    tags: ['user', 'remove', 'delete', 'deactivate'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconUserCheck',
    category: 'user',
    tags: ['user', 'verified', 'approved', 'confirmed'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── layout (6) ────────────────────────────────────────────────────
  {
    name: 'IconGrid',
    category: 'layout',
    tags: ['grid', 'tiles', 'gallery', 'matrix'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconList',
    category: 'layout',
    tags: ['list', 'rows', 'items', 'lines'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconColumns',
    category: 'layout',
    tags: ['columns', 'layout', 'split', 'vertical'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRows',
    category: 'layout',
    tags: ['rows', 'layout', 'split', 'horizontal'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPanelLeft',
    category: 'layout',
    tags: ['panel', 'sidebar', 'left', 'drawer'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPanelRight',
    category: 'layout',
    tags: ['panel', 'sidebar', 'right', 'drawer'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── data (8) ──────────────────────────────────────────────────────
  {
    name: 'IconBarChart',
    category: 'data',
    tags: ['bar', 'chart', 'graph', 'histogram', 'analytics'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLineChart',
    category: 'data',
    tags: ['line', 'chart', 'graph', 'trend', 'analytics'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPieChart',
    category: 'data',
    tags: ['pie', 'chart', 'donut', 'proportion', 'analytics'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTrendingUp',
    category: 'data',
    tags: ['trending', 'up', 'increase', 'growth', 'positive'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTrendingDown',
    category: 'data',
    tags: ['trending', 'down', 'decrease', 'decline', 'negative'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDatabase',
    category: 'data',
    tags: ['database', 'storage', 'server', 'data'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTable',
    category: 'data',
    tags: ['table', 'spreadsheet', 'grid', 'data', 'tabular'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHash',
    category: 'data',
    tags: ['hash', 'number', 'pound', 'tag', 'count'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── device (4) ────────────────────────────────────────────────────
  {
    name: 'IconSmartphone',
    category: 'device',
    tags: ['smartphone', 'phone', 'mobile', 'device'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLaptop',
    category: 'device',
    tags: ['laptop', 'computer', 'desktop', 'device'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconWatch',
    category: 'device',
    tags: ['watch', 'wearable', 'smartwatch', 'garmin'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBluetooth',
    category: 'device',
    tags: ['bluetooth', 'wireless', 'connect', 'pair'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── weather (4) ───────────────────────────────────────────────────
  {
    name: 'IconSun',
    category: 'weather',
    tags: ['sun', 'light', 'day', 'bright', 'weather'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCloud',
    category: 'weather',
    tags: ['cloud', 'overcast', 'sky', 'weather'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconThermometer',
    category: 'weather',
    tags: ['thermometer', 'temperature', 'heat', 'cold'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDroplet',
    category: 'weather',
    tags: ['droplet', 'water', 'rain', 'humidity'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── commerce (4) ──────────────────────────────────────────────────
  {
    name: 'IconCreditCard',
    category: 'commerce',
    tags: ['credit-card', 'payment', 'billing', 'stripe'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconShoppingCart',
    category: 'commerce',
    tags: ['shopping', 'cart', 'buy', 'store', 'ecommerce'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconReceipt',
    category: 'commerce',
    tags: ['receipt', 'invoice', 'bill', 'transaction'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPriceTag',
    category: 'commerce',
    tags: ['price', 'tag', 'label', 'discount', 'sale'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── toggle (7) ────────────────────────────────────────────────────
  {
    name: 'IconEye',
    category: 'toggle',
    tags: ['eye', 'visible', 'show', 'view', 'watch'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconEyeOff',
    category: 'toggle',
    tags: ['eye', 'hidden', 'hide', 'invisible', 'off'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLock',
    category: 'toggle',
    tags: ['lock', 'secure', 'private', 'closed'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconUnlock',
    category: 'toggle',
    tags: ['unlock', 'open', 'unsecure', 'public'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconStar',
    category: 'toggle',
    tags: ['star', 'favorite', 'rate', 'bookmark'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconStarFilled',
    category: 'toggle',
    tags: ['star', 'filled', 'favorite', 'rated', 'active'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBookmark',
    category: 'toggle',
    tags: ['bookmark', 'save', 'flag', 'pin'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── misc (8) ──────────────────────────────────────────────────────
  {
    name: 'IconGlobe',
    category: 'misc',
    tags: ['globe', 'world', 'earth', 'international', 'language'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMap',
    category: 'misc',
    tags: ['map', 'navigation', 'geography', 'route'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMapPin',
    category: 'misc',
    tags: ['map', 'pin', 'location', 'marker', 'gps'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconClock',
    category: 'misc',
    tags: ['clock', 'time', 'hour', 'schedule'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTimer',
    category: 'misc',
    tags: ['timer', 'stopwatch', 'countdown', 'lap'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRefresh',
    category: 'misc',
    tags: ['refresh', 'reload', 'sync', 'rotate', 'update'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: true,
  },
  {
    name: 'IconExternalLink',
    category: 'misc',
    tags: ['external', 'link', 'open', 'new-tab', 'outbound'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconQrCode',
    category: 'misc',
    tags: ['qr', 'code', 'scan', 'barcode'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── sport-domain (8) ──────────────────────────────────────────────
  {
    name: 'IconPower',
    category: 'sport-domain',
    tags: ['power', 'watts', 'watt', 'cycling', 'ftp'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHeartRate',
    category: 'sport-domain',
    tags: ['heart', 'rate', 'bpm', 'pulse', 'cardio'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: true,
  },
  {
    name: 'IconCadence',
    category: 'sport-domain',
    tags: ['cadence', 'rpm', 'pedal', 'rotation', 'cycling'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSpeed',
    category: 'sport-domain',
    tags: ['speed', 'velocity', 'pace', 'kmh', 'fast'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconElevation',
    category: 'sport-domain',
    tags: ['elevation', 'altitude', 'climb', 'mountain', 'ascent'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconGel',
    category: 'sport-domain',
    tags: ['gel', 'energy', 'sachet', 'race', 'fueling'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconGlycogen',
    category: 'sport-domain',
    tags: ['glycogen', 'storage', 'muscle', 'liver', 'energy'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconGut',
    category: 'sport-domain',
    tags: ['gut', 'intestine', 'absorption', 'digestion', 'gi'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── sport-training (8) ────────────────────────────────────────────
  {
    name: 'IconInterval',
    category: 'sport-training',
    tags: ['interval', 'hiit', 'workout', 'session', 'repeats'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconZone',
    category: 'sport-training',
    tags: ['zone', 'training-zone', 'intensity', 'threshold', 'band'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconThreshold',
    category: 'sport-training',
    tags: ['threshold', 'ftp', 'lactate', 'limit', 'boundary'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDurability',
    category: 'sport-training',
    tags: ['durability', 'endurance', 'fatigue', 'stamina', 'decay'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconResilience',
    category: 'sport-training',
    tags: ['resilience', 'bounce-back', 'adaptation', 'robustness'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPeakCurve',
    category: 'sport-training',
    tags: ['peak', 'curve', 'power-duration', 'best', 'record'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTrainingLoad',
    category: 'sport-training',
    tags: ['training', 'load', 'tss', 'stress', 'volume'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRecovery',
    category: 'sport-training',
    tags: ['recovery', 'rest', 'repair', 'regeneration', 'cool-down'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── sport-nutrition (8) ───────────────────────────────────────────
  {
    name: 'IconCHO',
    category: 'sport-nutrition',
    tags: ['cho', 'carbohydrate', 'carbs', 'sugar', 'glucose'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconProtein',
    category: 'sport-nutrition',
    tags: ['protein', 'amino', 'muscle', 'whey', 'macro'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFat',
    category: 'sport-nutrition',
    tags: ['fat', 'lipid', 'macro', 'omega', 'oil'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHydration',
    category: 'sport-nutrition',
    tags: ['hydration', 'water', 'fluid', 'drink', 'bottle'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSodium',
    category: 'sport-nutrition',
    tags: ['sodium', 'salt', 'electrolyte', 'mineral', 'sweat'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCaffeine',
    category: 'sport-nutrition',
    tags: ['caffeine', 'coffee', 'stimulant', 'alertness', 'boost'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMeal',
    category: 'sport-nutrition',
    tags: ['meal', 'food', 'eat', 'plate', 'nutrition'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSupplements',
    category: 'sport-nutrition',
    tags: ['supplements', 'vitamins', 'pills', 'capsule', 'stack'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconWheyProtein',
    category: 'sport-nutrition',
    tags: ['whey', 'protein', 'powder', 'tub', 'scoop', 'supplement'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCreatine',
    category: 'sport-nutrition',
    tags: ['creatine', 'supplement', 'powder', 'strength', 'atp', 'muscle'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBeetroot',
    category: 'sport-nutrition',
    tags: ['beetroot', 'nitrate', 'vegetable', 'vasodilation', 'endurance'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconIronSupplement',
    category: 'sport-nutrition',
    tags: ['iron', 'supplement', 'mineral', 'ferritin', 'anemia', 'tablet'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconVitaminD',
    category: 'sport-nutrition',
    tags: ['vitamin-d', 'sunshine', 'capsule', 'bone', 'immune', 'supplement'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconOmega3',
    category: 'sport-nutrition',
    tags: ['omega-3', 'fish-oil', 'softgel', 'dha', 'epa', 'anti-inflammatory'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconProbiotics',
    category: 'sport-nutrition',
    tags: ['probiotics', 'gut', 'bacteria', 'microbiome', 'digestion', 'capsule'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconElectrolyteMix',
    category: 'sport-nutrition',
    tags: ['electrolyte', 'drink-mix', 'hydration', 'effervescent', 'sodium', 'potassium'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── sport-body (8) ────────────────────────────────────────────────
  {
    name: 'IconSleep',
    category: 'sport-body',
    tags: ['sleep', 'rest', 'night', 'moon', 'recovery'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMuscle',
    category: 'sport-body',
    tags: ['muscle', 'strength', 'bicep', 'flex', 'body'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBrain',
    category: 'sport-body',
    tags: ['brain', 'mind', 'cognitive', 'mental', 'focus'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLungs',
    category: 'sport-body',
    tags: ['lungs', 'breathing', 'respiratory', 'vo2', 'oxygen'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconStomach',
    category: 'sport-body',
    tags: ['stomach', 'gut', 'digestion', 'gi', 'abdomen'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconAnatomicalHeart',
    category: 'sport-body',
    tags: ['heart', 'anatomical', 'cardiac', 'ventricle', 'aorta', 'organ'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconKneeJoint',
    category: 'sport-body',
    tags: ['knee', 'joint', 'femur', 'tibia', 'cartilage', 'meniscus'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSpine',
    category: 'sport-body',
    tags: ['spine', 'vertebrae', 'spinal', 'column', 'back', 'posture'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLiverOrgan',
    category: 'sport-body',
    tags: ['liver', 'organ', 'hepatic', 'detox', 'metabolism'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconKidney',
    category: 'sport-body',
    tags: ['kidney', 'renal', 'organ', 'filtration', 'ureter'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBoneStructure',
    category: 'sport-body',
    tags: ['bone', 'femur', 'skeleton', 'osseous', 'epiphysis'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTendon',
    category: 'sport-body',
    tags: ['tendon', 'ligament', 'connective', 'tissue', 'attachment'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMuscleFiber',
    category: 'sport-body',
    tags: ['muscle', 'fiber', 'myocyte', 'striation', 'bundle'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRedBloodCell',
    category: 'sport-body',
    tags: ['rbc', 'erythrocyte', 'blood', 'cell', 'biconcave', 'hemoglobin'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconNerve',
    category: 'sport-body',
    tags: ['nerve', 'neuron', 'axon', 'dendrite', 'synapse', 'neural'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconWeight',
    category: 'sport-body',
    tags: ['weight', 'scale', 'mass', 'kg', 'body-weight'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHRV',
    category: 'sport-body',
    tags: ['hrv', 'heart-rate-variability', 'autonomic', 'readiness'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconStress',
    category: 'sport-body',
    tags: ['stress', 'cortisol', 'tension', 'overreach', 'load'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── Batch 4: new icons (48) ────────────────────────────────────
  {
    name: 'IconUndo',
    category: 'action',
    tags: ['undo', 'back', 'revert', 'history'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRedo',
    category: 'action',
    tags: ['redo', 'forward', 'repeat'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSave',
    category: 'action',
    tags: ['save', 'floppy', 'disk', 'store'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPin',
    category: 'action',
    tags: ['pin', 'tack', 'attach', 'stick'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMoreVertical',
    category: 'action',
    tags: ['more', 'vertical', 'dots', 'menu', 'options'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMenu',
    category: 'action',
    tags: ['menu', 'hamburger', 'navigation', 'drawer'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMinus',
    category: 'action',
    tags: ['minus', 'remove', 'subtract', 'decrease'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconArrowUp',
    category: 'arrow',
    tags: ['arrow', 'up', 'move', 'direction'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconArrowDown',
    category: 'arrow',
    tags: ['arrow', 'down', 'move', 'direction'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCornerDownRight',
    category: 'arrow',
    tags: ['corner', 'redirect', 'arrow', 'turn'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconArrowUpDown',
    category: 'arrow',
    tags: ['sort', 'bidirectional', 'up', 'down', 'swap'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMoveVertical',
    category: 'arrow',
    tags: ['move', 'drag', 'vertical', 'reorder'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCheckCircle',
    category: 'status',
    tags: ['check', 'circle', 'success', 'done', 'confirmed'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconXCircle',
    category: 'status',
    tags: ['x', 'circle', 'error', 'close', 'cancel'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHelpCircle',
    category: 'status',
    tags: ['help', 'question', 'support', 'faq'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLoader',
    category: 'status',
    tags: ['loader', 'loading', 'spinner', 'progress'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBan',
    category: 'status',
    tags: ['ban', 'block', 'forbidden', 'prohibited', 'no'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFilePlus',
    category: 'file',
    tags: ['file', 'plus', 'add', 'new', 'create'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCode',
    category: 'file',
    tags: ['code', 'programming', 'developer', 'brackets'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTerminal',
    category: 'file',
    tags: ['terminal', 'command', 'cli', 'console', 'shell'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSidebar',
    category: 'layout',
    tags: ['sidebar', 'panel', 'navigation', 'drawer'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMaximize',
    category: 'layout',
    tags: ['maximize', 'fullscreen', 'expand', 'enlarge'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMinimize',
    category: 'layout',
    tags: ['minimize', 'exit-fullscreen', 'shrink', 'reduce'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSplitView',
    category: 'layout',
    tags: ['split', 'view', 'dual', 'columns', 'compare'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHome',
    category: 'navigation-app',
    tags: ['home', 'house', 'dashboard', 'main'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLogOut',
    category: 'navigation-app',
    tags: ['logout', 'signout', 'exit', 'leave'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLogIn',
    category: 'navigation-app',
    tags: ['login', 'signin', 'enter', 'access'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconInbox',
    category: 'navigation-app',
    tags: ['inbox', 'messages', 'mail', 'tray'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconNotification',
    category: 'navigation-app',
    tags: ['notification', 'bell', 'alert', 'remind'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSortAsc',
    category: 'sort',
    tags: ['sort', 'ascending', 'order', 'low-high'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSortDesc',
    category: 'sort',
    tags: ['sort', 'descending', 'order', 'high-low'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconChevronsUpDown',
    category: 'sort',
    tags: ['chevrons', 'updown', 'sort', 'select', 'expand'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconArrowDownAZ',
    category: 'sort',
    tags: ['sort', 'alpha', 'alphabetical', 'az', 'text'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCheckSquare',
    category: 'form',
    tags: ['checkbox', 'checked', 'square', 'form', 'input'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSquare',
    category: 'form',
    tags: ['square', 'checkbox', 'unchecked', 'empty', 'form'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCircleDot',
    category: 'form',
    tags: ['radio', 'selected', 'circle', 'dot', 'form'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCircle',
    category: 'form',
    tags: ['circle', 'radio', 'unselected', 'empty', 'form'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCalendarRange',
    category: 'form',
    tags: ['calendar', 'range', 'daterange', 'period', 'schedule'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconStrava',
    category: 'social',
    tags: ['strava', 'running', 'cycling', 'fitness', 'activity'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconGitHub',
    category: 'social',
    tags: ['github', 'git', 'code', 'repository', 'developer'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTwitter',
    category: 'social',
    tags: ['twitter', 'x', 'social', 'post', 'tweet'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconInstagram',
    category: 'social',
    tags: ['instagram', 'photo', 'camera', 'social', 'image'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconYouTube',
    category: 'social',
    tags: ['youtube', 'video', 'watch', 'streaming', 'media'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconApple',
    category: 'social',
    tags: ['apple', 'health', 'watch', 'ios', 'mac'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconThumbsUp',
    category: 'feedback',
    tags: ['thumbsup', 'like', 'approve', 'positive', 'good'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconThumbsDown',
    category: 'feedback',
    tags: ['thumbsdown', 'dislike', 'reject', 'negative', 'bad'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFlag',
    category: 'feedback',
    tags: ['flag', 'report', 'mark', 'milestone'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHeart',
    category: 'feedback',
    tags: ['heart', 'love', 'like', 'favorite', 'health'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  // ─── sport-race (10) ──────────────────────────────────────────────
  {
    name: 'IconRaceBib',
    category: 'sport-race',
    tags: ['bib', 'race', 'number', 'marathon', 'runner'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMedal',
    category: 'sport-race',
    tags: ['medal', 'award', 'winner', 'finisher', 'ribbon'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconStartLine',
    category: 'sport-race',
    tags: ['start', 'gate', 'arch', 'begin', 'race'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFinishLine',
    category: 'sport-race',
    tags: ['finish', 'banner', 'checkered', 'end', 'complete'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRaceVest',
    category: 'sport-race',
    tags: ['vest', 'singlet', 'tank', 'jersey', 'kit'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPodium',
    category: 'sport-race',
    tags: ['podium', 'winners', 'first', 'second', 'third', 'place'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconAidStation',
    category: 'sport-race',
    tags: ['aid', 'station', 'water', 'cup', 'hydration', 'flag'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSplitTime',
    category: 'sport-race',
    tags: ['split', 'time', 'stopwatch', 'lap', 'pace'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTransition',
    category: 'sport-race',
    tags: ['transition', 'triathlon', 'T1', 'T2', 'zone', 'change'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCourseMap',
    category: 'sport-race',
    tags: ['course', 'map', 'route', 'path', 'track'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  // ─── sport-biochem (12) ────────────────────────────────────────────────
  {
    name: 'IconMitochondria',
    category: 'sport-biochem',
    tags: ['mitochondria', 'cell', 'powerhouse', 'energy', 'organelle', 'cristae'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconATP',
    category: 'sport-biochem',
    tags: ['atp', 'adenosine', 'triphosphate', 'energy', 'molecule', 'phosphate'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDNAHelix',
    category: 'sport-biochem',
    tags: ['dna', 'helix', 'genetics', 'nucleotide', 'double-helix', 'genome'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCellMembrane',
    category: 'sport-biochem',
    tags: ['cell', 'membrane', 'phospholipid', 'bilayer', 'lipid', 'transport'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconGlucoseMolecule',
    category: 'sport-biochem',
    tags: ['glucose', 'sugar', 'pyranose', 'hexose', 'carbohydrate', 'fuel'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLactate',
    category: 'sport-biochem',
    tags: ['lactate', 'lactic-acid', 'threshold', 'anaerobic', 'metabolite'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconO2',
    category: 'sport-biochem',
    tags: ['oxygen', 'O2', 'respiration', 'aerobic', 'molecule', 'gas'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHemoglobin',
    category: 'sport-biochem',
    tags: ['hemoglobin', 'haemoglobin', 'blood', 'iron', 'protein', 'oxygen-transport'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconEnzyme',
    category: 'sport-biochem',
    tags: ['enzyme', 'catalyst', 'protein', 'active-site', 'substrate', 'lock-key'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconAminoAcid',
    category: 'sport-biochem',
    tags: ['amino-acid', 'protein', 'peptide', 'amine', 'carboxyl', 'R-group'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFattyAcid',
    category: 'sport-biochem',
    tags: ['fatty-acid', 'lipid', 'fat', 'chain', 'carboxyl', 'beta-oxidation'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconInsulinMolecule',
    category: 'sport-biochem',
    tags: ['insulin', 'hormone', 'hexamer', 'pancreas', 'glucose-regulation', 'protein'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  // ─── Wave 10: UI + Activity + Weather + Food + Unique (58) ──────
  {
    name: 'IconShield',
    category: 'security',
    tags: ['shield', 'protect', 'security', 'guard', 'safe', 'defense'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconShieldCheck',
    category: 'security',
    tags: ['shield', 'verified', 'secure', 'protected', 'check', 'trust'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconKey',
    category: 'security',
    tags: ['key', 'access', 'auth', 'password', 'unlock', 'api'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFingerprint',
    category: 'security',
    tags: ['fingerprint', 'biometric', 'identity', 'scan', 'touch', 'auth'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTrophy',
    category: 'achievement',
    tags: ['trophy', 'cup', 'win', 'champion', 'prize', 'pr'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCrown',
    category: 'achievement',
    tags: ['crown', 'king', 'queen', 'royal', 'best', 'leaderboard'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTarget',
    category: 'achievement',
    tags: ['target', 'goal', 'aim', 'focus', 'objective', 'bullseye'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMountainFlag',
    category: 'achievement',
    tags: ['mountain', 'flag', 'summit', 'peak', 'accomplish', 'climb', 'goal'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconAward',
    category: 'achievement',
    tags: ['award', 'ribbon', 'badge', 'certificate', 'honor', 'recognition'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconStreak',
    category: 'achievement',
    tags: ['streak', 'fire', 'flame', 'hot', 'consecutive', 'burning'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconZap',
    category: 'achievement',
    tags: ['zap', 'lightning', 'bolt', 'energy', 'fast', 'quick', 'power'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconToggleOn',
    category: 'toggle',
    tags: ['toggle', 'on', 'switch', 'enabled', 'active'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconToggleOff',
    category: 'toggle',
    tags: ['toggle', 'off', 'switch', 'disabled', 'inactive'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSliders',
    category: 'toggle',
    tags: ['sliders', 'adjust', 'controls', 'equalizer', 'preferences'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconGauge',
    category: 'data',
    tags: ['gauge', 'speedometer', 'meter', 'dashboard', 'performance'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPercent',
    category: 'data',
    tags: ['percent', 'percentage', 'rate', 'ratio', 'proportion'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconWifi',
    category: 'device',
    tags: ['wifi', 'wireless', 'signal', 'internet', 'network', 'connection'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBattery',
    category: 'device',
    tags: ['battery', 'power', 'charge', 'energy', 'level', 'wearable'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCalendarCheck',
    category: 'form',
    tags: ['calendar', 'check', 'done', 'completed', 'scheduled', 'confirmed'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCalendarPlus',
    category: 'form',
    tags: ['calendar', 'plus', 'add', 'create', 'new', 'event'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRepeat',
    category: 'action',
    tags: ['repeat', 'loop', 'cycle', 'recurring', 'again', 'reload'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconAlarm',
    category: 'misc',
    tags: ['alarm', 'clock', 'wake', 'reminder', 'alert', 'morning'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSparkles',
    category: 'action',
    tags: ['sparkles', 'magic', 'ai', 'generate', 'new', 'enhance', 'stars'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRocket',
    category: 'action',
    tags: ['rocket', 'launch', 'boost', 'fast', 'startup', 'deploy'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLayers',
    category: 'layout',
    tags: ['layers', 'stack', 'depth', 'z-index', 'overlap'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPalette',
    category: 'misc',
    tags: ['palette', 'color', 'theme', 'art', 'design', 'customize'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCompass',
    category: 'misc',
    tags: ['compass', 'navigate', 'direction', 'explore', 'outdoor', 'north'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLanguage',
    category: 'misc',
    tags: ['language', 'translate', 'i18n', 'locale', 'bilingual', 'da', 'en'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBike',
    category: 'activity',
    tags: ['bike', 'bicycle', 'cycling', 'ride', 'road', 'velo'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRunning',
    category: 'activity',
    tags: ['running', 'run', 'jog', 'sprint', 'trail', 'marathon'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSwimming',
    category: 'activity',
    tags: ['swimming', 'swim', 'pool', 'triathlon', 'water', 'freestyle'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDumbbell',
    category: 'activity',
    tags: ['dumbbell', 'gym', 'strength', 'weight', 'lift', 'training'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconYoga',
    category: 'activity',
    tags: ['yoga', 'stretch', 'flexibility', 'pose', 'meditation', 'balance'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHiking',
    category: 'activity',
    tags: ['hiking', 'walk', 'trail', 'mountain', 'outdoor', 'trek'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRowing',
    category: 'activity',
    tags: ['rowing', 'row', 'ergometer', 'erg', 'kayak', 'paddle'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSkiing',
    category: 'activity',
    tags: ['skiing', 'ski', 'winter', 'snow', 'downhill', 'nordic'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconWind',
    category: 'weather',
    tags: ['wind', 'breeze', 'gust', 'air', 'headwind', 'cycling'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRain',
    category: 'weather',
    tags: ['rain', 'rainy', 'wet', 'precipitation', 'shower', 'weather'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSnow',
    category: 'weather',
    tags: ['snow', 'snowflake', 'winter', 'cold', 'frost', 'ice'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMoon',
    category: 'weather',
    tags: ['moon', 'night', 'dark', 'crescent', 'sleep', 'evening'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSunrise',
    category: 'weather',
    tags: ['sunrise', 'morning', 'dawn', 'early', 'am', 'day'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSunset',
    category: 'weather',
    tags: ['sunset', 'evening', 'dusk', 'pm', 'golden', 'late'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconStorm',
    category: 'weather',
    tags: ['storm', 'thunder', 'lightning', 'severe', 'weather', 'electric'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCoffee',
    category: 'food',
    tags: ['coffee', 'cup', 'drink', 'caffeine', 'espresso', 'morning'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconWaterBottle',
    category: 'food',
    tags: ['water', 'bottle', 'hydrate', 'drink', 'fluid', 'sport'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconForkKnife',
    category: 'food',
    tags: ['fork', 'knife', 'eat', 'meal', 'dining', 'restaurant', 'nutrition'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBlender',
    category: 'food',
    tags: ['blender', 'smoothie', 'mix', 'shake', 'protein', 'kitchen'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconKitchenScale',
    category: 'food',
    tags: ['scale', 'weigh', 'measure', 'food', 'portion', 'gram', 'kitchen'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRoute',
    category: 'misc',
    tags: ['route', 'gps', 'path', 'trail', 'track', 'navigation', 'outdoor'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHeadwind',
    category: 'weather',
    tags: ['headwind', 'resistance', 'against', 'cycling', 'wind', 'face'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTailwind',
    category: 'weather',
    tags: ['tailwind', 'boost', 'push', 'cycling', 'wind', 'behind', 'fast'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconGradientSlope',
    category: 'activity',
    tags: ['gradient', 'slope', 'incline', 'hill', 'climb', 'grade', 'elevation'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconStopwatch',
    category: 'misc',
    tags: ['stopwatch', 'timing', 'lap', 'race', 'countdown', 'chrono'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPulse',
    category: 'data',
    tags: ['pulse', 'ecg', 'heartbeat', 'vital', 'signal', 'wave', 'health'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDashboardPanel',
    category: 'data',
    tags: ['dashboard', 'panel', 'overview', 'metrics', 'summary', 'multi'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSplitArrow',
    category: 'data',
    tags: ['split', 'diverge', 'branch', 'decision', 'ab', 'fork', 'path'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRPE',
    category: 'sport-training',
    tags: ['rpe', 'perceived', 'exertion', 'effort', 'rating', 'subjective', 'feel'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconNutritionPlan',
    category: 'sport-nutrition',
    tags: ['nutrition', 'plan', 'strategy', 'race', 'fueling', 'timeline'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  // ─── Sport equipment/lab backfill (23) ──────────────────────────
  {
    name: 'IconBiopsy',
    category: 'sport-biochem',
    tags: ['biopsy', 'tissue', 'sample', 'muscle', 'lab'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBloodSample',
    category: 'sport-biochem',
    tags: ['blood', 'sample', 'test', 'draw', 'lab'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBodyComposition',
    category: 'sport-body',
    tags: ['body', 'composition', 'dexa', 'scan', 'fat'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCentrifuge',
    category: 'sport-biochem',
    tags: ['centrifuge', 'spin', 'lab', 'separate', 'blood'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCompressionSock',
    category: 'sport-race',
    tags: ['compression', 'sock', 'recovery', 'calf', 'gear'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFoamRoller',
    category: 'sport-race',
    tags: ['foam', 'roller', 'massage', 'recovery', 'myofascial'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconJumpRope',
    category: 'sport-race',
    tags: ['jump', 'rope', 'skip', 'cardio', 'warmup'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconKettlebell',
    category: 'sport-race',
    tags: ['kettlebell', 'weight', 'swing', 'strength', 'gym'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLabFlask',
    category: 'sport-biochem',
    tags: ['flask', 'erlenmeyer', 'lab', 'chemistry', 'science'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLactateStrip',
    category: 'sport-biochem',
    tags: ['lactate', 'strip', 'test', 'portable', 'field'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLactateThreshold',
    category: 'sport-training',
    tags: ['lactate', 'threshold', 'lt', 'anaerobic', 'inflection'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMicroscope',
    category: 'sport-biochem',
    tags: ['microscope', 'lab', 'magnify', 'research', 'science'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPetriDish',
    category: 'sport-biochem',
    tags: ['petri', 'dish', 'culture', 'lab', 'biology'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPullUpBar',
    category: 'sport-race',
    tags: ['pullup', 'bar', 'calisthenics', 'strength', 'bodyweight'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconResistanceBand',
    category: 'sport-race',
    tags: ['resistance', 'band', 'elastic', 'stretch', 'warmup'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRunningShoe',
    category: 'sport-race',
    tags: ['running', 'shoe', 'sneaker', 'footwear', 'race'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSoftFlask',
    category: 'sport-race',
    tags: ['soft', 'flask', 'hydration', 'handheld', 'running'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSwimGoggles',
    category: 'sport-race',
    tags: ['swim', 'goggles', 'pool', 'triathlon', 'water'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTempo',
    category: 'sport-training',
    tags: ['tempo', 'pace', 'rhythm', 'steady', 'endurance'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTestTube',
    category: 'sport-biochem',
    tags: ['test', 'tube', 'lab', 'sample', 'chemistry'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconUrineSample',
    category: 'sport-biochem',
    tags: ['urine', 'sample', 'hydration', 'test', 'lab'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconVO2Max',
    category: 'sport-body',
    tags: ['vo2', 'max', 'oxygen', 'aerobic', 'capacity'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconYogaMat',
    category: 'sport-race',
    tags: ['yoga', 'mat', 'stretch', 'flexibility', 'warmup'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  // ─── Wave 11: Training Science + Race Strategy + Fun (38) ──────
  {
    name: 'IconSuperCompensation',
    category: 'sport-training',
    tags: ['supercompensation', 'adaptation', 'overload', 'recovery', 'peak', 'science'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTaper',
    category: 'sport-training',
    tags: ['taper', 'reduce', 'volume', 'pre-race', 'peak', 'rest'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPeriodization',
    category: 'sport-training',
    tags: ['periodization', 'plan', 'block', 'base', 'build', 'peak', 'race', 'cycle'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconOverreach',
    category: 'sport-training',
    tags: ['overreach', 'overtrain', 'burnout', 'exceed', 'limit', 'redzone', 'danger'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDeload',
    category: 'sport-training',
    tags: ['deload', 'recovery', 'easy', 'light', 'week', 'reduce', 'planned'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFatigueResistance',
    category: 'sport-training',
    tags: ['fatigue', 'resistance', 'durability', 'endurance', 'decay', 'drop', 'flat'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconNegativeSplit',
    category: 'sport-race',
    tags: ['negative', 'split', 'pacing', 'faster', 'second-half', 'strategy'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDrafting',
    category: 'sport-race',
    tags: ['drafting', 'slipstream', 'peloton', 'wheel', 'aero', 'group', 'cycling'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBonk',
    category: 'sport-race',
    tags: ['bonk', 'wall', 'glycogen', 'empty', 'crash', 'depletion', 'hunger'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPacing',
    category: 'sport-race',
    tags: ['pacing', 'even', 'steady', 'consistent', 'effort', 'split', 'strategy'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconAeroDrag',
    category: 'sport-domain',
    tags: ['aero', 'drag', 'aerodynamic', 'cda', 'wind', 'resistance', 'position'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDecoupling',
    category: 'sport-domain',
    tags: ['decoupling', 'drift', 'cardiac', 'aerobic', 'hr', 'power', 'efficiency'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPowerProfile',
    category: 'sport-domain',
    tags: ['power', 'profile', 'radar', 'spider', 'strengths', 'weaknesses', 'chart'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconVerticalOscillation',
    category: 'sport-domain',
    tags: ['vertical', 'oscillation', 'bounce', 'running', 'form', 'efficiency'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconGroundContact',
    category: 'sport-domain',
    tags: ['ground', 'contact', 'time', 'gct', 'running', 'form', 'foot', 'strike'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCadenceOptimal',
    category: 'sport-domain',
    tags: ['cadence', 'optimal', 'sweet-spot', 'rpm', 'zone', 'efficiency', 'dial'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconIceBath',
    category: 'sport-body',
    tags: ['ice', 'bath', 'cold', 'therapy', 'plunge', 'recovery', 'cryotherapy'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDOMS',
    category: 'sport-body',
    tags: ['doms', 'delayed', 'onset', 'muscle', 'soreness', 'stiffness', 'pain'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCompression',
    category: 'sport-body',
    tags: ['compression', 'garment', 'recovery', 'squeeze', 'pressure', 'circulation'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconActiveRecovery',
    category: 'sport-body',
    tags: ['active', 'recovery', 'easy', 'zone1', 'light', 'movement', 'walk'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSleepScore',
    category: 'sport-body',
    tags: ['sleep', 'score', 'quality', 'stages', 'rem', 'deep', 'light', 'readiness'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCarboLoading',
    category: 'sport-nutrition',
    tags: ['carbo', 'loading', 'glycogen', 'pre-race', 'fuel', 'storage', 'supercompensate'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconGutTraining',
    category: 'sport-nutrition',
    tags: ['gut', 'training', 'tolerance', 'absorption', 'practice', 'gi', 'stomach'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconAbsorptionRate',
    category: 'sport-nutrition',
    tags: ['absorption', 'rate', 'uptake', 'gut', 'gram', 'hour', 'flow', 'transport'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFuelingWindow',
    category: 'sport-nutrition',
    tags: ['fueling', 'window', 'timing', 'post', 'workout', 'anabolic', 'golden', 'hour'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFlowState',
    category: 'sport-body',
    tags: ['flow', 'state', 'zone', 'focus', 'peak', 'performance', 'mindfulness'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconWhistle',
    category: 'user',
    tags: ['whistle', 'coach', 'referee', 'instructor', 'trainer', 'blow'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSeasonBest',
    category: 'achievement',
    tags: ['season', 'best', 'sb', 'personal', 'record', 'calendar', 'achievement'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTSB',
    category: 'sport-training',
    tags: ['tsb', 'training', 'stress', 'balance', 'form', 'fitness', 'fatigue', 'pmc'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMentalToughness',
    category: 'sport-body',
    tags: ['mental', 'toughness', 'grit', 'resilience', 'mind', 'strong', 'fortitude'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPizzaSlice',
    category: 'food',
    tags: ['pizza', 'cheat', 'meal', 'reward', 'rest', 'day', 'treat', 'fun'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBeer',
    category: 'food',
    tags: ['beer', 'post-race', 'celebrate', 'reward', 'pint', 'cheers', 'fun'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconUnicorn',
    category: 'achievement',
    tags: ['unicorn', 'rare', 'magical', 'impossible', 'legendary', 'pr', 'dream', 'fun'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconChickenLeg',
    category: 'food',
    tags: ['chicken', 'protein', 'meat', 'meal', 'leg', 'drumstick', 'recovery', 'fun'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSockTan',
    category: 'activity',
    tags: ['sock', 'tan', 'cycling', 'tanline', 'summer', 'rider', 'badge', 'fun'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconShameFridge',
    category: 'food',
    tags: ['fridge', 'shame', 'midnight', 'snack', 'guilty', 'pleasure', 'cheat', 'fun'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDNF',
    category: 'sport-race',
    tags: ['dnf', 'did-not-finish', 'abandon', 'quit', 'dropout', 'bail', 'walk'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCouchPotato',
    category: 'activity',
    tags: ['couch', 'rest', 'lazy', 'off', 'day', 'potato', 'netflix', 'fun', 'recovery'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
]
