// Copyright (c) 2026 RAMTT (Malte Therkildsen)
// Licensed under MIT OR Apache-2.0. See LICENSE-MIT and LICENSE-APACHE.

// @ramtt/icons — Icon catalog metadata (184 icons × 25 categories)

export interface IconMeta {
  name: string
  category: string
  tags: string[]
  hasLine: boolean
  hasSolid: boolean
  hasDuo: boolean
  hasAnimated: boolean
}

export const ICON_CATEGORIES = [
  'navigation',
  'action',
  'arrow',
  'status',
  'communication',
  'media',
  'file',
  'user',
  'layout',
  'data',
  'device',
  'weather',
  'commerce',
  'toggle',
  'misc',
  'sport-domain',
  'sport-training',
  'sport-nutrition',
  'sport-body',
  'navigation-app',
  'sort',
  'form',
  'social',
  'feedback',
  'sport-race',
] as const

export const ICON_CATALOG: IconMeta[] = [
  // ─── navigation (5) ────────────────────────────────────────────────
  {
    name: 'IconToday',
    category: 'navigation',
    tags: ['today', 'date', 'now', 'current'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCalendar',
    category: 'navigation',
    tags: ['calendar', 'date', 'schedule', 'planner'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconAnalytics',
    category: 'navigation',
    tags: ['analytics', 'dashboard', 'stats', 'insights'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFuel',
    category: 'navigation',
    tags: ['fuel', 'nutrition', 'energy', 'carbs'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSettings',
    category: 'navigation',
    tags: ['settings', 'preferences', 'config', 'gear', 'cog'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── action (13) ───────────────────────────────────────────────────
  {
    name: 'IconPlus',
    category: 'action',
    tags: ['plus', 'add', 'create', 'new'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconClose',
    category: 'action',
    tags: ['close', 'dismiss', 'remove', 'x'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSearch',
    category: 'action',
    tags: ['search', 'find', 'lookup', 'magnifier'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFilter',
    category: 'action',
    tags: ['filter', 'funnel', 'sort', 'refine'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconEdit',
    category: 'action',
    tags: ['edit', 'pencil', 'modify', 'write'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTrash',
    category: 'action',
    tags: ['trash', 'delete', 'remove', 'bin'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCopy',
    category: 'action',
    tags: ['copy', 'duplicate', 'clipboard', 'paste'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDownload',
    category: 'action',
    tags: ['download', 'save', 'export', 'arrow-down'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconUpload',
    category: 'action',
    tags: ['upload', 'import', 'arrow-up', 'send'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: true,
  },
  {
    name: 'IconExpand',
    category: 'action',
    tags: ['expand', 'fullscreen', 'maximize', 'enlarge'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCollapse',
    category: 'action',
    tags: ['collapse', 'minimize', 'shrink', 'reduce'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMoreHorizontal',
    category: 'action',
    tags: ['more', 'dots', 'ellipsis', 'menu', 'options'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconGrip',
    category: 'action',
    tags: ['grip', 'drag', 'handle', 'reorder', 'move'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── arrow (6) ─────────────────────────────────────────────────────
  {
    name: 'IconChevronLeft',
    category: 'arrow',
    tags: ['chevron', 'left', 'back', 'previous'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconChevronRight',
    category: 'arrow',
    tags: ['chevron', 'right', 'next', 'forward'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconChevronDown',
    category: 'arrow',
    tags: ['chevron', 'down', 'dropdown', 'expand'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconChevronUp',
    category: 'arrow',
    tags: ['chevron', 'up', 'collapse', 'above'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconArrowLeft',
    category: 'arrow',
    tags: ['arrow', 'left', 'back', 'navigate'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconArrowRight',
    category: 'arrow',
    tags: ['arrow', 'right', 'forward', 'navigate'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── status (4) ────────────────────────────────────────────────────
  {
    name: 'IconCheck',
    category: 'status',
    tags: ['check', 'done', 'success', 'complete', 'tick'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: true,
  },
  {
    name: 'IconAlertTriangle',
    category: 'status',
    tags: ['alert', 'warning', 'triangle', 'caution'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconInfo',
    category: 'status',
    tags: ['info', 'information', 'help', 'about'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconAlertCircle',
    category: 'status',
    tags: ['alert', 'error', 'circle', 'danger', 'exclamation'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── communication (8) ─────────────────────────────────────────────
  {
    name: 'IconMail',
    category: 'communication',
    tags: ['mail', 'email', 'envelope', 'message'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSend',
    category: 'communication',
    tags: ['send', 'submit', 'paper-plane', 'dispatch'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMessageCircle',
    category: 'communication',
    tags: ['message', 'chat', 'bubble', 'circle', 'comment'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMessageSquare',
    category: 'communication',
    tags: ['message', 'chat', 'bubble', 'square', 'comment'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPhone',
    category: 'communication',
    tags: ['phone', 'call', 'telephone', 'contact'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconVideo',
    category: 'communication',
    tags: ['video', 'camera', 'record', 'meeting'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconShare',
    category: 'communication',
    tags: ['share', 'forward', 'distribute', 'social'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLink',
    category: 'communication',
    tags: ['link', 'url', 'chain', 'hyperlink', 'connect'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── media (6) ─────────────────────────────────────────────────────
  {
    name: 'IconImage',
    category: 'media',
    tags: ['image', 'photo', 'picture', 'gallery'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCamera',
    category: 'media',
    tags: ['camera', 'photo', 'capture', 'snapshot'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPlay',
    category: 'media',
    tags: ['play', 'start', 'video', 'media'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPause',
    category: 'media',
    tags: ['pause', 'stop', 'halt', 'media'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconVolume',
    category: 'media',
    tags: ['volume', 'sound', 'audio', 'speaker'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMic',
    category: 'media',
    tags: ['mic', 'microphone', 'audio', 'voice', 'record'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── file (6) ──────────────────────────────────────────────────────
  {
    name: 'IconFile',
    category: 'file',
    tags: ['file', 'document', 'page', 'blank'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFileText',
    category: 'file',
    tags: ['file', 'text', 'document', 'content', 'article'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFolder',
    category: 'file',
    tags: ['folder', 'directory', 'organize', 'group'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFolderOpen',
    category: 'file',
    tags: ['folder', 'open', 'directory', 'browse'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconClipboard',
    category: 'file',
    tags: ['clipboard', 'paste', 'copy', 'board'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconArchive',
    category: 'file',
    tags: ['archive', 'box', 'storage', 'compress'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── user (5) ──────────────────────────────────────────────────────
  {
    name: 'IconUser',
    category: 'user',
    tags: ['user', 'person', 'profile', 'account'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconUsers',
    category: 'user',
    tags: ['users', 'people', 'group', 'team', 'members'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconUserPlus',
    category: 'user',
    tags: ['user', 'add', 'invite', 'new-member'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconUserMinus',
    category: 'user',
    tags: ['user', 'remove', 'delete', 'deactivate'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconUserCheck',
    category: 'user',
    tags: ['user', 'verified', 'approved', 'confirmed'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── layout (6) ────────────────────────────────────────────────────
  {
    name: 'IconGrid',
    category: 'layout',
    tags: ['grid', 'tiles', 'gallery', 'matrix'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconList',
    category: 'layout',
    tags: ['list', 'rows', 'items', 'lines'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconColumns',
    category: 'layout',
    tags: ['columns', 'layout', 'split', 'vertical'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRows',
    category: 'layout',
    tags: ['rows', 'layout', 'split', 'horizontal'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPanelLeft',
    category: 'layout',
    tags: ['panel', 'sidebar', 'left', 'drawer'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPanelRight',
    category: 'layout',
    tags: ['panel', 'sidebar', 'right', 'drawer'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── data (8) ──────────────────────────────────────────────────────
  {
    name: 'IconBarChart',
    category: 'data',
    tags: ['bar', 'chart', 'graph', 'histogram', 'analytics'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLineChart',
    category: 'data',
    tags: ['line', 'chart', 'graph', 'trend', 'analytics'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPieChart',
    category: 'data',
    tags: ['pie', 'chart', 'donut', 'proportion', 'analytics'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTrendingUp',
    category: 'data',
    tags: ['trending', 'up', 'increase', 'growth', 'positive'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTrendingDown',
    category: 'data',
    tags: ['trending', 'down', 'decrease', 'decline', 'negative'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDatabase',
    category: 'data',
    tags: ['database', 'storage', 'server', 'data'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTable',
    category: 'data',
    tags: ['table', 'spreadsheet', 'grid', 'data', 'tabular'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHash',
    category: 'data',
    tags: ['hash', 'number', 'pound', 'tag', 'count'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── device (4) ────────────────────────────────────────────────────
  {
    name: 'IconSmartphone',
    category: 'device',
    tags: ['smartphone', 'phone', 'mobile', 'device'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLaptop',
    category: 'device',
    tags: ['laptop', 'computer', 'desktop', 'device'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconWatch',
    category: 'device',
    tags: ['watch', 'wearable', 'smartwatch', 'garmin'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBluetooth',
    category: 'device',
    tags: ['bluetooth', 'wireless', 'connect', 'pair'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── weather (4) ───────────────────────────────────────────────────
  {
    name: 'IconSun',
    category: 'weather',
    tags: ['sun', 'light', 'day', 'bright', 'weather'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCloud',
    category: 'weather',
    tags: ['cloud', 'overcast', 'sky', 'weather'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconThermometer',
    category: 'weather',
    tags: ['thermometer', 'temperature', 'heat', 'cold'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDroplet',
    category: 'weather',
    tags: ['droplet', 'water', 'rain', 'humidity'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── commerce (4) ──────────────────────────────────────────────────
  {
    name: 'IconCreditCard',
    category: 'commerce',
    tags: ['credit-card', 'payment', 'billing', 'stripe'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconShoppingCart',
    category: 'commerce',
    tags: ['shopping', 'cart', 'buy', 'store', 'ecommerce'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconReceipt',
    category: 'commerce',
    tags: ['receipt', 'invoice', 'bill', 'transaction'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPriceTag',
    category: 'commerce',
    tags: ['price', 'tag', 'label', 'discount', 'sale'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── toggle (7) ────────────────────────────────────────────────────
  {
    name: 'IconEye',
    category: 'toggle',
    tags: ['eye', 'visible', 'show', 'view', 'watch'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconEyeOff',
    category: 'toggle',
    tags: ['eye', 'hidden', 'hide', 'invisible', 'off'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLock',
    category: 'toggle',
    tags: ['lock', 'secure', 'private', 'closed'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconUnlock',
    category: 'toggle',
    tags: ['unlock', 'open', 'unsecure', 'public'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconStar',
    category: 'toggle',
    tags: ['star', 'favorite', 'rate', 'bookmark'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconStarFilled',
    category: 'toggle',
    tags: ['star', 'filled', 'favorite', 'rated', 'active'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBookmark',
    category: 'toggle',
    tags: ['bookmark', 'save', 'flag', 'pin'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── misc (8) ──────────────────────────────────────────────────────
  {
    name: 'IconGlobe',
    category: 'misc',
    tags: ['globe', 'world', 'earth', 'international', 'language'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMap',
    category: 'misc',
    tags: ['map', 'navigation', 'geography', 'route'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMapPin',
    category: 'misc',
    tags: ['map', 'pin', 'location', 'marker', 'gps'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconClock',
    category: 'misc',
    tags: ['clock', 'time', 'hour', 'schedule'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTimer',
    category: 'misc',
    tags: ['timer', 'stopwatch', 'countdown', 'lap'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRefresh',
    category: 'misc',
    tags: ['refresh', 'reload', 'sync', 'rotate', 'update'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: true,
  },
  {
    name: 'IconExternalLink',
    category: 'misc',
    tags: ['external', 'link', 'open', 'new-tab', 'outbound'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconQrCode',
    category: 'misc',
    tags: ['qr', 'code', 'scan', 'barcode'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── sport-domain (8) ──────────────────────────────────────────────
  {
    name: 'IconPower',
    category: 'sport-domain',
    tags: ['power', 'watts', 'watt', 'cycling', 'ftp'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHeartRate',
    category: 'sport-domain',
    tags: ['heart', 'rate', 'bpm', 'pulse', 'cardio'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: true,
  },
  {
    name: 'IconCadence',
    category: 'sport-domain',
    tags: ['cadence', 'rpm', 'pedal', 'rotation', 'cycling'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSpeed',
    category: 'sport-domain',
    tags: ['speed', 'velocity', 'pace', 'kmh', 'fast'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconElevation',
    category: 'sport-domain',
    tags: ['elevation', 'altitude', 'climb', 'mountain', 'ascent'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconGel',
    category: 'sport-domain',
    tags: ['gel', 'energy', 'sachet', 'race', 'fueling'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconGlycogen',
    category: 'sport-domain',
    tags: ['glycogen', 'storage', 'muscle', 'liver', 'energy'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconGut',
    category: 'sport-domain',
    tags: ['gut', 'intestine', 'absorption', 'digestion', 'gi'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── sport-training (8) ────────────────────────────────────────────
  {
    name: 'IconInterval',
    category: 'sport-training',
    tags: ['interval', 'hiit', 'workout', 'session', 'repeats'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconZone',
    category: 'sport-training',
    tags: ['zone', 'training-zone', 'intensity', 'threshold', 'band'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconThreshold',
    category: 'sport-training',
    tags: ['threshold', 'ftp', 'lactate', 'limit', 'boundary'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconDurability',
    category: 'sport-training',
    tags: ['durability', 'endurance', 'fatigue', 'stamina', 'decay'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconResilience',
    category: 'sport-training',
    tags: ['resilience', 'bounce-back', 'adaptation', 'robustness'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPeakCurve',
    category: 'sport-training',
    tags: ['peak', 'curve', 'power-duration', 'best', 'record'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTrainingLoad',
    category: 'sport-training',
    tags: ['training', 'load', 'tss', 'stress', 'volume'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRecovery',
    category: 'sport-training',
    tags: ['recovery', 'rest', 'repair', 'regeneration', 'cool-down'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── sport-nutrition (8) ───────────────────────────────────────────
  {
    name: 'IconCHO',
    category: 'sport-nutrition',
    tags: ['cho', 'carbohydrate', 'carbs', 'sugar', 'glucose'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconProtein',
    category: 'sport-nutrition',
    tags: ['protein', 'amino', 'muscle', 'whey', 'macro'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFat',
    category: 'sport-nutrition',
    tags: ['fat', 'lipid', 'macro', 'omega', 'oil'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHydration',
    category: 'sport-nutrition',
    tags: ['hydration', 'water', 'fluid', 'drink', 'bottle'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSodium',
    category: 'sport-nutrition',
    tags: ['sodium', 'salt', 'electrolyte', 'mineral', 'sweat'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCaffeine',
    category: 'sport-nutrition',
    tags: ['caffeine', 'coffee', 'stimulant', 'alertness', 'boost'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMeal',
    category: 'sport-nutrition',
    tags: ['meal', 'food', 'eat', 'plate', 'nutrition'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSupplements',
    category: 'sport-nutrition',
    tags: ['supplements', 'vitamins', 'pills', 'capsule', 'stack'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── sport-body (8) ────────────────────────────────────────────────
  {
    name: 'IconSleep',
    category: 'sport-body',
    tags: ['sleep', 'rest', 'night', 'moon', 'recovery'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMuscle',
    category: 'sport-body',
    tags: ['muscle', 'strength', 'bicep', 'flex', 'body'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBrain',
    category: 'sport-body',
    tags: ['brain', 'mind', 'cognitive', 'mental', 'focus'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLungs',
    category: 'sport-body',
    tags: ['lungs', 'breathing', 'respiratory', 'vo2', 'oxygen'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconStomach',
    category: 'sport-body',
    tags: ['stomach', 'gut', 'digestion', 'gi', 'abdomen'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconWeight',
    category: 'sport-body',
    tags: ['weight', 'scale', 'mass', 'kg', 'body-weight'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHRV',
    category: 'sport-body',
    tags: ['hrv', 'heart-rate-variability', 'autonomic', 'readiness'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconStress',
    category: 'sport-body',
    tags: ['stress', 'cortisol', 'tension', 'overreach', 'load'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },

  // ─── Batch 4: new icons (48) ────────────────────────────────────
  {
    name: 'IconUndo',
    category: 'action',
    tags: ['undo', 'back', 'revert', 'history'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRedo',
    category: 'action',
    tags: ['redo', 'forward', 'repeat'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSave',
    category: 'action',
    tags: ['save', 'floppy', 'disk', 'store'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPin',
    category: 'action',
    tags: ['pin', 'tack', 'attach', 'stick'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMoreVertical',
    category: 'action',
    tags: ['more', 'vertical', 'dots', 'menu', 'options'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMenu',
    category: 'action',
    tags: ['menu', 'hamburger', 'navigation', 'drawer'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMinus',
    category: 'action',
    tags: ['minus', 'remove', 'subtract', 'decrease'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconArrowUp',
    category: 'arrow',
    tags: ['arrow', 'up', 'move', 'direction'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconArrowDown',
    category: 'arrow',
    tags: ['arrow', 'down', 'move', 'direction'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCornerDownRight',
    category: 'arrow',
    tags: ['corner', 'redirect', 'arrow', 'turn'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconArrowUpDown',
    category: 'arrow',
    tags: ['sort', 'bidirectional', 'up', 'down', 'swap'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMoveVertical',
    category: 'arrow',
    tags: ['move', 'drag', 'vertical', 'reorder'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCheckCircle',
    category: 'status',
    tags: ['check', 'circle', 'success', 'done', 'confirmed'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconXCircle',
    category: 'status',
    tags: ['x', 'circle', 'error', 'close', 'cancel'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHelpCircle',
    category: 'status',
    tags: ['help', 'question', 'support', 'faq'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLoader',
    category: 'status',
    tags: ['loader', 'loading', 'spinner', 'progress'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconBan',
    category: 'status',
    tags: ['ban', 'block', 'forbidden', 'prohibited', 'no'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFilePlus',
    category: 'file',
    tags: ['file', 'plus', 'add', 'new', 'create'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCode',
    category: 'file',
    tags: ['code', 'programming', 'developer', 'brackets'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTerminal',
    category: 'file',
    tags: ['terminal', 'command', 'cli', 'console', 'shell'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSidebar',
    category: 'layout',
    tags: ['sidebar', 'panel', 'navigation', 'drawer'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMaximize',
    category: 'layout',
    tags: ['maximize', 'fullscreen', 'expand', 'enlarge'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMinimize',
    category: 'layout',
    tags: ['minimize', 'exit-fullscreen', 'shrink', 'reduce'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSplitView',
    category: 'layout',
    tags: ['split', 'view', 'dual', 'columns', 'compare'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHome',
    category: 'navigation-app',
    tags: ['home', 'house', 'dashboard', 'main'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLogOut',
    category: 'navigation-app',
    tags: ['logout', 'signout', 'exit', 'leave'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconLogIn',
    category: 'navigation-app',
    tags: ['login', 'signin', 'enter', 'access'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconInbox',
    category: 'navigation-app',
    tags: ['inbox', 'messages', 'mail', 'tray'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconNotification',
    category: 'navigation-app',
    tags: ['notification', 'bell', 'alert', 'remind'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSortAsc',
    category: 'sort',
    tags: ['sort', 'ascending', 'order', 'low-high'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSortDesc',
    category: 'sort',
    tags: ['sort', 'descending', 'order', 'high-low'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconChevronsUpDown',
    category: 'sort',
    tags: ['chevrons', 'updown', 'sort', 'select', 'expand'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconArrowDownAZ',
    category: 'sort',
    tags: ['sort', 'alpha', 'alphabetical', 'az', 'text'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCheckSquare',
    category: 'form',
    tags: ['checkbox', 'checked', 'square', 'form', 'input'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSquare',
    category: 'form',
    tags: ['square', 'checkbox', 'unchecked', 'empty', 'form'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCircleDot',
    category: 'form',
    tags: ['radio', 'selected', 'circle', 'dot', 'form'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCircle',
    category: 'form',
    tags: ['circle', 'radio', 'unselected', 'empty', 'form'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCalendarRange',
    category: 'form',
    tags: ['calendar', 'range', 'daterange', 'period', 'schedule'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconStrava',
    category: 'social',
    tags: ['strava', 'running', 'cycling', 'fitness', 'activity'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconGitHub',
    category: 'social',
    tags: ['github', 'git', 'code', 'repository', 'developer'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTwitter',
    category: 'social',
    tags: ['twitter', 'x', 'social', 'post', 'tweet'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconInstagram',
    category: 'social',
    tags: ['instagram', 'photo', 'camera', 'social', 'image'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconYouTube',
    category: 'social',
    tags: ['youtube', 'video', 'watch', 'streaming', 'media'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconApple',
    category: 'social',
    tags: ['apple', 'health', 'watch', 'ios', 'mac'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconThumbsUp',
    category: 'feedback',
    tags: ['thumbsup', 'like', 'approve', 'positive', 'good'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconThumbsDown',
    category: 'feedback',
    tags: ['thumbsdown', 'dislike', 'reject', 'negative', 'bad'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFlag',
    category: 'feedback',
    tags: ['flag', 'report', 'mark', 'milestone'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconHeart',
    category: 'feedback',
    tags: ['heart', 'love', 'like', 'favorite', 'health'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  // ─── sport-race (10) ──────────────────────────────────────────────
  {
    name: 'IconRaceBib',
    category: 'sport-race',
    tags: ['bib', 'race', 'number', 'marathon', 'runner'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconMedal',
    category: 'sport-race',
    tags: ['medal', 'award', 'winner', 'finisher', 'ribbon'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconStartLine',
    category: 'sport-race',
    tags: ['start', 'gate', 'arch', 'begin', 'race'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconFinishLine',
    category: 'sport-race',
    tags: ['finish', 'banner', 'checkered', 'end', 'complete'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconRaceVest',
    category: 'sport-race',
    tags: ['vest', 'singlet', 'tank', 'jersey', 'kit'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconPodium',
    category: 'sport-race',
    tags: ['podium', 'winners', 'first', 'second', 'third', 'place'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconAidStation',
    category: 'sport-race',
    tags: ['aid', 'station', 'water', 'cup', 'hydration', 'flag'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconSplitTime',
    category: 'sport-race',
    tags: ['split', 'time', 'stopwatch', 'lap', 'pace'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconTransition',
    category: 'sport-race',
    tags: ['transition', 'triathlon', 'T1', 'T2', 'zone', 'change'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
  {
    name: 'IconCourseMap',
    category: 'sport-race',
    tags: ['course', 'map', 'route', 'path', 'track'],
    hasLine: true,
    hasSolid: true,
    hasDuo: true,
    hasAnimated: false,
  },
]
